site:
  title: Crux
  start_page: main::index.adoc
content:
  sources:
    - url: ../
      start_path: docs/main
      branches: HEAD
    - url: ../
      start_path: docs/about
      branches: HEAD
    - url: ../
      start_path: docs/tutorials
      branches: HEAD
#   - url: https://github.com/juxt/crux
#      start_path: docs/reference
#      branches:
#        - example-version-branch
#      tag:
#        - release-version
    - url: ../
      start_path: docs/reference
      branches: HEAD
ui:
  bundle:
    url: ./crux-site/ui-bundle.zip
    snapshot: true
